Add to_s to image_id in order to fix "ActionView::Template::Error: undefined method `downcase' for XYZ:Integer" caused by foreman images_helper.rb
(cherry picked from commit a41b9eaec6a53f937bbfcf0f4db06b0f4f76f253)